[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#778DA9"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#F0F6FC"

[client]
caching = true
showErrorDetails = false 